
version: '3.7'

services:
  mlflow-server:
    image: continuumio/miniconda3
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      bash -c "mlflow server --host 0.0.0.0 --port 5000"

  iris-ml-app:
    build: .
    container_name: iris-ml-app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    volumes:
      - .:/app
    depends_on:
      - mlflow-server

